### ISSUE TITLE
Problem with MessageBus.RunOnUIThread method on Android

### ISSUE THREAD

**Issue by kmalmur** [newky2k/MessageBus#1]
It seems that MessageBus.RunOnUIThread doesn't work.

The reason is not initialized SyncContext field.

**Comment by trevoriancox** [comment]
Yes, there's a bug, there's currently no way to initialize synccontext. But with this fix, you have to make sure the MessageBus object is instantiated from the UI thread. In other words the function is really be "RunOnOriginalThread"...

**Comment by newky2k** [comment]
Implemented in latest versions
