### ISSUE TITLE
Each event is posted in a new task

### ISSUE THREAD

**Issue by kmalmur** [newky2k/MessageBus#3]
I don't understand why every event must be posted with a separate task. It only adds additional level of client code complexity and introduces some overhead of course. 

If there are two components working in one thread (Android example: an Activity and a fragment), there is no reason why posting a new event should be done i a new Task. 

As an example you can have a look on the very popular EventBus Android library, it works as I suggested.

**Comment by newky2k** [comment]
Implemented in latest version
